services:
  kazgirls-frontend:
    image: kazgirls-frontend
    restart: unless-stopped
    container_name: kazgirls-frontend
    hostname: kazgirls-frontend
    env_file:
      - kazgirls-frontend-docker.env
    ports:
      - "80:80"
    depends_on:
      - kazgirls-api

  kazgirls-api:
    image: kazgirls-api
    restart: unless-stopped
    container_name: kazgirls-api
    hostname: kazgirls-api
    env_file:
      - kazgirls-api-docker.env
    volumes:
      - /var/lib/kazgirls/kazgirls-storage-data:/var/lib/kazgirls/storage
      - /var/log/kazgirls/app-logs:/var/log/kazgirls/
    depends_on:
      - kazgirls-db
      - kazgirls-redis

  kazgirls-jobs:
    image: kazgirls-api
    restart: unless-stopped
    container_name: kazgirls-jobs
    hostname: kazgirls-jobs
    env_file:
      - kazgirls-api-docker.env
    depends_on:
      - kazgirls-db
      - kazgirls-redis
    volumes:
      - /var/log/kazgirls/app-logs:/var/log/kazgirls/
    entrypoint: ["arq", "job_worker.Worker"]

  kazgirls-migrate:
    image: kazgirls-api
    container_name: kazgirls-migrate
    entrypoint: alembic upgrade head
    env_file:
      - kazgirls-api-docker.env
