version: "2"
services:
  kazgirls-frontend:
    image: kazgirls-frontend
    restart: unless-stopped
    container_name: kazgirls-frontend
    hostname: kazgirls-frontend
    env_file:
      - kazgirls-frontend-docker.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - kazgirls-api
    logging:
      driver: local
      options:
        max-size: "20m"
        max-file: "10"
        compress: "false"
        mode: "non-blocking"
        max-buffer-size: "10m"

  kazgirls-api:
    image: kazgirls-api
    restart: unless-stopped
    container_name: kazgirls-api
    hostname: kazgirls-api
    env_file:
      - kazgirls-api-docker.env
    volumes:
      - /var/lib/kazgirls/kazgirls-storage-data:/var/lib/kazgirls/storage
      - /var/log/kazgirls/app-logs:/var/log/kazgirls/
    logging:
      driver: local
      options:
        max-size: "20m"
        max-file: "10"
        compress: "false"
        mode: "non-blocking"
        max-buffer-size: "10m"

  kazgirls-jobs:
    image: kazgirls-api
    restart: unless-stopped
    container_name: kazgirls-jobs
    hostname: kazgirls-jobs
    env_file:
      - kazgirls-api-docker.env
    volumes:
      - /var/log/kazgirls/app-logs:/var/log/kazgirls/
    entrypoint: ["arq", "job_worker.Worker"]
    logging:
      driver: local
      options:
        max-size: "20m"
        max-file: "10"
        compress: "false"
        mode: "non-blocking"
        max-buffer-size: "10m"

  kazgirls-migrate:
    image: kazgirls-api
    container_name: kazgirls-migrate
    entrypoint: alembic upgrade head
    env_file:
      - kazgirls-api-docker.env
